### PR TITLE
Buildsystem enhancements

### PR DESCRIPTION
**Pull request by manisandro**
This pull request enhances the build system to make it easier to package the library for Linux distribution. It enhances the following aspects:

- Allow building with system libraries
- Add install target
- Add soname
- Add check target

The default behavior remains unchanged: it builds the static library with the bundled libraries. Question however is whether the library should be named libpdfhummus instead of libPDFWriter (and also headers installed to /usr/include/pdfhummus).

As a next step, it would also be nice to introduce a package version.

### CODE REVIEW

**Comment by galkahana** [comment]
Hi,
I would like to merge this sometime soon.
Could you please provide some text on which flags exist now for cmake and how they work?
(specifically is there a behavior change from what is described in this text:
https://github.com/galkahana/PDF-Writer/wiki/Building-and-running-samples#special-options-with-cmake)

Gal.

**Comment by manisandro** [comment]
The only new flag is `USE_BUNDLED` which defaults to `TRUE`. If `USE_BUNDLED=TRUE`, the behaviour is identical to the old behaviour.

If `USE_BUNDLED=FALSE`, system libraries for `libjpeg, libtiff, freetype, libaesgm, zlib` are searched. `PDFHUMMUS_NO_DCT` and `PDFHUMMUS_NO_TIFF` are set depending on whether the corresponding system libraries could be found. The other libraries are mandatory and cmake configuration will fail if the libraries could not be found.

**Comment by fajan** [comment]
As @galkahana asked for my opinion: 
Probably a configurable include options ( such as `LIBJPEG_INCLUDE_DIR`, `LIBJPEG_LIB_DIR`  etc) which overrides bundled or pkg_search-ed packages would be nice. 

I also vote for libpdfhummus and package version :D
And for that: release versions could be tagged, so sources for each realeas would be available here too.

**Comment by galkahana** [comment]
Thanks @manisandro  and @fajan.
loving the new check target :)

**Comment by galkahana** [comment]
bothered me enough so i created package configuration for hummus. with how cmake advanced and me deciding to learn some more cmake we're now able to install PDFHummus and then use it in another project as a package. And it also works by installing from remote with `FetchContent`.

**Pull request merged**
