### PR TITLE
Supporting ICU in BIDI

### PR DESCRIPTION
**Pull request by amrnablus**
@galkahana I just added support for doing the BiDi using libICU, here are some notes:
1. By default the library will build with both ICU And Fribidi, and use friBidi, if you'd like to make ICU default, the build needs to be done with`-DPDFHUMMUS_NO_FRIBIDI=1`
2. If you want to completely disable bidi, add those two flags: `-DPDFHUMMUS_NO_FRIBIDI=1 -DPDFHUMMUS_NO_ICUBIDI=1`
3. For some reason, i get this error while building if i run cmake with no flags: `make[2]: *** No rule to make target '../libIcu/source/build/lib/libfribidi.a', needed by 'PDFWriterTestPlayground/PDFWriterTestPlayground'.  Stop.`

### CODE REVIEW

**Comment by galkahana** [comment]
Thanks man. Re 3. Any particular reason that you want to keep freebidi? I guess if you remove you still got icu, and the problem would go away. No?

**Comment by amrnablus** [comment]
Well the main reason is that the library is smaller than icu, if you check
the cmake file you'll notice that you have to link 5.a files from icu to
make things work vs 1 file from fribidi. My feeling is that fribidi is also
faster, i can run some benchmarks and see if that's true.
If you're concerned about the license we could always make icu the default

**Comment by galkahana** [comment]
Makes sense. Let's keep frigidi as an option.

**Comment by amrnablus** [comment]
Hey @galkahana , any idea when you're planning to merge?

**Comment by galkahana** [comment]
Busy at present, which is why im delaying. I need to review, cleanup, see how to make it work for pc or if not remove by default, see if i can make it work for hummusjs too. Theres a bit of work that ill do and than ill merge.

**Comment by amrnablus** [comment]
Alright thanks man, let me know if i can help with any of those (except making it work for PC)

**Comment by galkahana** [comment]
sure :)

**Comment by galkahana** [comment]
after many years. got to BIDI support through a different project of mine, of trying to parse text out of pdf.
for this i needed an inverse conversion, but the principal is the same. in any case, what's difficult is the building process, which now there's an example that you can use. this is the project - https://github.com/galkahana/pdf-text-extraction
specifically, building of icu bidi is done [here](https://github.com/galkahana/pdf-text-extraction/blob/master/TextExtraction/CMakeLists.txt#L73) (under condition of USE_BIDI, which you can remove).

code usage is [here](https://github.com/galkahana/pdf-text-extraction/blob/master/TextExtraction/lib/bidi/BidiConversion.cpp) but do note that this is about parsing, and normally you'd be using this for writing, and amrnablus code [here](https://github.com/galkahana/PDF-Writer/pull/65/files#diff-3a663c72b61402022375a9a6fdbaf16fR25) is more aligned to what you'd need (as well as includes conversion to the location-aware unicode char so that the final glyph looks correct per its position in the word).

**Comment by galkahana** [comment]
Pdfhummus wont inclide icu support. You can build an icu solution on top of it though, as explained here and theres a good example.

**Pull request closed without merging**
